const path = require('path');

module.exports = {
  // The core directory where agents, templates, etc., are stored.
  corePath: '.stigmergy-core',

  // The directory for AI-generated artifacts and state.
  aiArtifacts: '.ai',

  // Central state file for the autonomous loop.
  stateFile: path.join('.ai', 'state.json'),

  // Directory where stories generated by the PM are stored.
  storiesPath: path.join('.ai', 'stories'),

  // Directory for system improvement proposals from the @meta agent.
  proposalsPath: 'system-proposals',

  // Key project documents.
  docs: {
    prd: 'docs/prd.md',
    architecture: 'docs/architecture.md',
  },

  // Setting to control which executor agent is used.
  // This makes the dispatcher's logic much cleaner.
  use_gemini_executor: true,
};
