import fs from "fs-extra";
import path from "path";
import yaml from "js-yaml";
import { fileURLToPath } from "url";
import { dirname } from "path";

export async function configureIde(
  coreSourceDir,
  outputPath = path.join(process.cwd(), ".roomodes")
) {
  const PORT = process.env.PORT || 3000;
  const ENGINE_URL = `http://localhost:${PORT}`;

  // 1. Load the agent manifest
  const manifestPath = path.join(coreSourceDir, "system_docs", "02_Agent_Manifest.md");
  const manifestContent = await fs.readFile(manifestPath, "utf8");
  const manifestYamlMatch = manifestContent.match(/```(?:yaml|yml)\n([\s\S]*?)\s*```/);
  if (!manifestYamlMatch) {
    throw new Error(`Could not parse YAML from manifest file: ${manifestPath}`);
  }
  const manifest = yaml.load(manifestYamlMatch[1]);

  // 2. Create customModes array
  const customModes = [];

  for (const agent of manifest.agents) {
    const agentFilePath = path.join(coreSourceDir, "agents", `${agent.id}.md`);

    if (await fs.pathExists(agentFilePath)) {
      // 1. Read the RAW file content to use as the roleDefinition
      const rawAgentDefinition = await fs.readFile(agentFilePath, "utf8");

      // 2. Parse the YAML from the file to get structured data
      const yamlMatch = rawAgentDefinition.match(/```(?:yaml|yml)\n([\s\S]*?)\s*```/);

      if (yamlMatch && yamlMatch[1]) {
        try {
          const agentData = yaml.load(yamlMatch[1]);

          // 3. Initialize variables for the new structure
          const finalGroups = [];
          let source = null; // Default to null

          // 4. Correctly parse the 'tools' array
          const tools = agentData.tools || []; // Ensure tools is an array
          for (const tool of tools) {
            if (tool.startsWith("mcpsource:")) {
              // If it's a source directive, extract the value
              source = tool.split(":")[1].trim();
            } else {
              // Otherwise, it's a normal group
              finalGroups.push(tool);
            }
          }

          // 5. Build the final customMode object with the correct structure
          const mode = {
            slug: agentData.agent.alias,
            name: `${agentData.agent.icon} ${agentData.agent.name}`,
            roleDefinition: rawAgentDefinition, // Use the full raw definition
            groups: finalGroups, // Use the filtered groups
            api: {
              url: `${ENGINE_URL}/api/chat`,
              method: "POST",
              include: ["history"],
              // Add the static_payload as seen in the correct example
              static_payload: {
                agentId: agentData.agent.id,
              },
            },
          };

          // 6. Only add the source key if it was found
          if (source) {
            mode.source = source;
          }

          customModes.push(mode);
        } catch (e) {
          console.warn(`Skipping agent due to YAML parse error in ${agent.id}: ${e.message}`);
        }
      }
    }
  }

  customModes.unshift(
    {
      slug: "system-resume",
      name: "▶️ Resume Engine",
      roleDefinition: "Resume the autonomous engine.",
      api: { url: `${ENGINE_URL}/api/control/resume`, method: "POST" },
      groups: ["command"],
    },
    {
      slug: "system-pause",
      name: "⏸️ Pause Engine",
      roleDefinition: "Pause the autonomous engine.",
      api: { url: `${ENGINE_URL}/api/control/pause`, method: "POST" },
      groups: ["command"],
    }
  );

  // 3. Sort modes alphabetically by name
  customModes.sort((a, b) => a.name.localeCompare(b.name));

  // 4. Generate the YAML output with CORRECT format
  const yamlOutput = yaml.dump({ customModes: customModes }, { lineWidth: -1 });
  const fileContent = `# This file is auto-generated by 'stigmergy install'.\n\n${yamlOutput}`;
  await fs.writeFile(outputPath, fileContent, "utf8");
}

async function install() {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  console.log("Stigmergy install process started...");
  const targetDir = process.cwd();
  const sourceDir = path.resolve(__dirname, "../../.stigmergy-core");

  try {
    const destStigmergyDir = path.join(targetDir, ".stigmergy-core");
    if (!(await fs.pathExists(destStigmergyDir))) {
      await fs.copy(sourceDir, destStigmergyDir);
      console.log(`Copied .stigmergy-core to ${targetDir}`);
    }

    await configureIde(destStigmergyDir);

    console.log(`✅ Install complete. .roomodes file created.`);
    return true;
  } catch (error) {
    console.error("❌ An unexpected error occurred during the install process:");
    console.error(error);
    return false;
  }
}

export { install };
